### ISSUE TITLE
compiling error descriptors.cpp

### ISSUE THREAD

**Issue by janzeiringer** [tomasz-grobelny/AACS#1]
Hello, i have an issue while compiling. The log says that the headerfile functionfs.h is missing in descriptors.cpp
thanks

/home/jan/AA/AACS/AAServer/src/descriptors.cpp:4:10: fatal error: functionfs.h: No such file or directory
    4 | #include "functionfs.h"
      |          ^~~~~~~~~~~~~~
compilation terminated.
make[2]: *** [AAServer/CMakeFiles/AAServer.dir/build.make:153: AAServer/CMakeFiles/AAServer.dir/src/descriptors.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:165: AAServer/CMakeFiles/AAServer.dir/all] Error 2
make: *** [Makefile:84: all] Error 2

**Comment by tomasz-grobelny** [comment]
This functionfs.h file comes from "/opt/linux/include/uapi/linux/usb/" directory where /opt/linux contains linux kernel headers. Finding kernel headers should probably be a little bit more generic, but I need time to work on it.

**Comment by janzeiringer** [comment]
Thanks for your help
Great Projekt
