### ISSUE TITLE
functionalities with Car Android Auto headunit 

### ISSUE THREAD

**Issue by lucav90** [tomasz-grobelny/AACS#2]
Hi,

i m very interest about your software.
i have an android auto headunit on my car (original opel intellilink 4.0).
i want to use an old phone to connect permatly to android auto of my car but it is not good.

With your software is possibile to use a Odroid N2, connect it on usb of my car, and diplay on my screen car a custom view using the androidauto headunit?
if yes, it's great! it is possible simulte android phone but more clean and without all android auto app limits.

regards,

**Comment by tomasz-grobelny** [comment]
Theoretically yes. Note, however, that this is very early stage of development and I had only chance to test on my VW family car. I tried testing on Fiat Tipo, but didn't work out of the box - more testing to come. If you wish to test on Opel - great, I should be able to provide guidance, but do not expect it to work without problems at first try.

**Comment by lucav90** [comment]
Ok! But the problem Is: i havent the odroid  n2 board.
I have only a Arduino uno. 
It a possible another way?

**Comment by tomasz-grobelny** [comment]
I am afraid that Arduino might not be powerful enough - the communication is based on H264 format so the board need to be powerful enough to encode H264 video signal at headunit's resolution (here it is 800x480) and crypt/decrypt at the same time (SSL).

**Comment by lucav90** [comment]
I think Arduino Is not good for this. 
I want spend Money to buy a board only for a test.
A Raspberry Pi 3,4 is ok for this?
Your code Is good for a Raspberry?

**Comment by tomasz-grobelny** [comment]
RPi should be powerful enough, but AFAIK it cannot be connected in USB gadget mode.

**Comment by janzeiringer** [comment]
I think that the raspberry pi 4 support usb gadget (dwc2)

**Comment by lucav90** [comment]
The code on your repo and your istruction are able with Raspberry 4? So if i found a board by friends, i can try to use it, and then we can try to write istruction and test result for this device and my car

**Comment by tomasz-grobelny** [comment]
If so, then you can give it a try. Code should theoretically work with any board that has gadget mode enabled in kernel (5.4+ requited). Might be some scripts will require fine tuning.

**Comment by lucav90** [comment]
it is good Raspberry Pi 0?

**Comment by janzeiringer** [comment]
In theory yes. But i think that the raspberry pi zero has not enough power for that.

**Comment by lucav90** [comment]
my friend has a Raspberry pi 3 not 4 so i haven't device to test it and i can't buy a board only for a test.
